on:
  issues:
    types: [opened]
    
jobs:
  issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: display
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: run query
        run: |
          curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [ {"role": "systme", "content": "You are a helpful github assistant. You will respond to users in a markdown friendly format. You should provide an explination to you r solution as well as a code snippet"},
                          {"role": "user", "content": "${{ github.event.issue.body }}" }],
              "temperature": 0.7
                }'
      
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Wow That's great
